[build]
builder = "nixpacks"
buildCommand = "npm install --include=dev && npm install --prefix api && npm run build"

[deploy]
startCommand = "node api/server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production.variables]
NODE_ENV = "production"
